-- AlterTable
ALTER TABLE "users" ADD COLUMN     "businessAddress" TEXT,
ADD COLUMN     "businessCity" TEXT,
ADD COLUMN     "businessCountry" TEXT DEFAULT 'United States',
ADD COLUMN     "businessEmail" TEXT,
ADD COLUMN     "businessLogo" TEXT,
ADD COLUMN     "businessPhone" TEXT,
ADD COLUMN     "businessState" TEXT,
ADD COLUMN     "businessWebsite" TEXT,
ADD COLUMN     "businessZipCode" TEXT,
ADD COLUMN     "dateFormat" TEXT DEFAULT 'MM/DD/YYYY',
ADD COLUMN     "defaultInvoiceNotes" TEXT,
ADD COLUMN     "defaultInvoiceTerms" TEXT,
ADD COLUMN     "invoiceNumberPrefix" TEXT DEFAULT 'INV',
ADD COLUMN     "language" TEXT DEFAULT 'en',
ADD COLUMN     "nextInvoiceNumber" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "stripeAccountStatus" TEXT,
ADD COLUMN     "stripeChargesEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stripeConnectedAt" TIMESTAMP(3),
ADD COLUMN     "stripeOnboardingComplete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stripePayoutsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timezone" TEXT DEFAULT 'UTC';
